from decimal import Decimal
import datetime

def convert_to_property_code(data):
    """
    Recebe um dicionário de dados no formato chave: valor e gera os setProperty correspondentes.
    """
    property_code = ""
    
    # Função para converter data em timestamp
    def convert_to_timestamp(value):
        try:
            # Convertendo string para datetime, em seguida para o formato Timestamp do Java
            timestamp = datetime.datetime.strptime(value, "%Y-%m-%d %H:%M:%S.%f")
            return f'Timestamp("{timestamp.strftime("%Y-%m-%d %H:%M:%S")}")'
        except ValueError:
            return value
    
    for key, value in data.items():
        if value is None:
            property_code += f'seuVOPojo.setProperty("{key}", null);\n'
        elif isinstance(value, str):
            # Se for string, apenas adicionar
            property_code += f'seuVOPojo.setProperty("{key}", "{value}");\n'
        elif isinstance(value, bool):
            # Se for booleano, converter para "S" ou "N"
            property_code += f'seuVOPojo.setProperty("{key}", "{("S" if value else "N")}");\n'
        elif isinstance(value, Decimal):
            # Se for Decimal (BigDecimal)
            property_code += f'seuVOPojo.setProperty("{key}", new BigDecimal({value}));\n'
        elif isinstance(value, datetime.datetime):
            # Se for uma data
            property_code += f'seuVOPojo.setProperty("{key}", {convert_to_timestamp(value)});\n'
        else:
            # Para outros tipos (se necessário, adicione tratamentos adicionais)
            property_code += f'seuVOPojo.setProperty("{key}", "{value}");\n'
    
    return property_code


# Exemplo de dados que você passaria
data = {"PRZREGCANNOTA": Decimal('24')
        ,"CALCVLRAQUISBEM": None
        ,"RECMINTARE": "N"
        ,"CODTABCKC": Decimal('0')
        ,"CAMCONVPREF": None
        ,"CentroResultadoIpi": None
        ,"ModeloDACTE": None
        ,"FormulaPrecificacao": None
        ,"PERCCOFINS": Decimal('0')
        ,"TOPCANPIXPAG": None
        ,"ULTNSU": Decimal('0')
        ,"NOTAENTAJUSTESTCTER": None
        ,"TOPCANPIXREC": None
        ,"TOPDESPESA": None
        ,"CAEPF": None
        ,"ESTRNCREDICMSST": "N"
        ,"DIFALIQDESPACESS": None
        ,"ATIVO": "S"
        ,"IMPETIQVOLCONF": "N"
        ,"TRATARTRIBUT": "N"
        ,"CODLANCBCOPAG": Decimal('2')
        ,"ULTAUTORPAG": None
        ,"CODLANCBCOREC": Decimal('1')
        ,"DESTIPIDEVCOM": None
        ,"BAIXAFINPREEMISSNFCE": None
        ,"PERFILEFD": "A"
        ,"USAMEDDIAIMP": None
        ,"ModeloRetornoEstoqueWMS": None
        ,"UTILIZAEXPLOTE": None
        ,"CODCTACTBMULT": None
        ,"SENHAECT": None
        ,"PESMAXSEPAGRU": None
        ,"CODCTACTB_2": None
        ,"ENDEMOVINDEF": None
        ,"ParceiroEntrega": None
        ,"CODCTACTB_3": None
        ,"VERSAONTMDFE": Decimal('9999')
        ,"APIKEYPIXCHECKOUT": "7091108b03ffbef01368e181e0050756b9a1a5b4"
        ,"CODCTACTB_1": None
        ,"MAXNOTASLOTENFE": None
        ,"CLASCONS_ENERG": None
        ,"TPASSINANTEINF": "N"
        ,"NURFECARTACORRCTE": None
        ,"PREFIXSERIENACIONAL": None
        ,"CODLOCALTERC": None
        ,"COPIASDANFCE": None
        ,"NOTASAIPERDAWMS": None
        ,"TOPENVWMSAGRUP": None
        ,"ModeloEmail2": None
        ,"TOPDEVOLUCAOWMS": None
        ,"INTERVALO": Decimal('15')
        ,"ModeloSaidaReclassificacao": None
        ,"TRANSPCARGA": Decimal('1')
        ,"CONTINGENCIACTE": None
        ,"GRAVARSERIENOTA": "N"
        ,"TRIBPISCFMULT": "N"
        ,"DIRFENTIMUNE": None
        ,"TIPCTACTBEFDF": None
        ,"FRASENFSE": None
        ,"DEFCSTIPI03": None
        ,"DEFCSTIPI04": None
        ,"DEFCSTIPI01": None
        ,"DEFCSTIPI02": None
        ,"DEFCSTIPI00": None
        ,"CODENDRETEXP": None
        ,"EnderecoArmazenagemIndefinida": None
        ,"ModeloEtiqueta": None
        ,"CODEMPMATRIZNFSE": None
        ,"EnderecoArmazenagemIndef": None
        ,"DEFCSTIPI05": None
        ,"Natureza": None
        ,"SITEMPREINF": None
        ,"EmpresaMatrizGnre": None
        ,"VLRUNITMERC": None
        ,"CONSDIFPARCOUTICMS": None
        ,"VLRUNITICMSOP": None
        ,"IPINAOINCID": "I"
        ,"CHAVEDIGITALAGILIBLUE": None
        ,"LOGODANFE": "Repo://impressao/logo.png"
        ,"NOTAENTAJUSTESTDTER": None
        ,"USAINDPRESTOPFAT": None
        ,"BANCOPIXCHECKOUT": Decimal('1')
        ,"CODENQIPISAI": None
        ,"IMPRESSORAETQVOL": None
        ,"MODEXPED": None
        ,"ICMSNORMALDIFICMSSN": None
        ,"ModeloDanfe": None
        ,"AGRUPASERVFAT": None
        ,"COMPLRESTITUICAOICMSST": "N"
        ,"VLRLIQITEMNFE": None
        ,"REDPISBCPISCOFINS": None
        ,"ULTPAGLIVSAIDA": None
        ,"EnderecoArmazenagem5": None
        ,"PERCCFFAB": None
        ,"EnderecoArmazenagem4": None
        ,"EnderecoArmazenagem3": None
        ,"CODMODNFCECOMPL": None
        ,"TipoOperacaoEFDEmpresa": None
        ,"EnderecoRetornoExpedicao": None
        ,"WMSCODENDFLUT": None
        ,"CentroResultado": None
        ,"INSXMLPORIMPSMTPXML": None
        ,"USUARIOSMTPXML": None
        ,"ALIQCFDESC": None
        ,"ModeloEntradaReclassificacao": None
        ,"TEMDENUESPONT": "N"
        ,"NOTASAIAJUSTBEM": None
        ,"CORFIXADO": Decimal('10987389')
        ,"EnderecoArmazenagem2": None
        ,"ModeloDanfeNFCeCompleto": None
        ,"FRAGMENTAESTWMS": "N"
        ,"TOPCANPIXFIN": None
        ,"ContaBancariaIpi": None
        ,"DESCREDDIFCIAP": None
        ,"URLPIXCHECKOUT": "https://pix-instantaneo.sankhya.com.br"
        ,"CALPERCPIS": None
        ,"EFDCODBCO": None
        ,"NFSEOBSITERPS": None
        ,"TERACPCTE": None
        ,"PlanoContaEmpresa2": None
        ,"PlanoContaEmpresa3": None
        ,"CODUSUNFSE": None
        ,"GEROBSFING4000": None
        ,"TOKENIBPT": None
        ,"NUNOTATRCFX": Decimal('7')
        ,"WMSUSAREGVOLFAT": "N"
        ,"CODTABCALC": Decimal('0')
        ,"TPOBSNOTAG4000": None
        ,"CODENDPERDA": None
        ,"WMSUSAIMPFECHAVOL": None
        ,"ENVLEITRANSPDESC": None
        ,"ISALIQINTSEXC": None
        ,"REDSTCOMPBCPISCOFINS": None
        ,"ModeloSaidaEstoqueDeTerc": None
        ,"SERNAOTRIBBASEISS": "N"
        ,"ENVMDFSINC": None
        ,"TEMPIS": "S"
        ,"TOPRECARGACELECONECT": None
        ,"CODMODDANFESIMPLIFNFE": Decimal('3')
        ,"TPAMBNFCOM": None
        ,"CONTINGENCIANFE": "F"
        ,"CODCTABCOIPAD": None
        ,"VLRICMSOPANT": None
        ,"ENTREGAECD": "N"
        ,"EnderecoCrossDocking": None
        ,"FRETESEPCONSTRANSP": "N"
        ,"INTCONSSMTPXML": None
        ,"DEFCSTIPI50": None
        ,"DEFCSTIPI51": None
        ,"TPLIGACAOINF": "N"
        ,"APLCALCDIFALIQFRT": None
        ,"TOPENTRADAWMS": None
        ,"DTVALFINREINF": None
        ,"TEMPREMIACAOESTADUAL": None
        ,"SENHAECTRASTREIO": None
        ,"GERMULTPLACRES": None
        ,"ALIQPISBONIF": None
        ,"CODEMPOC": None
        ,"PlanoContaMulta": None
        ,"DIRFSOCOST": None
        ,"CREDICMSREMG": None
        ,"SALDOLIVQUINZ": "M"
        ,"CODENDSOBRA": None
        ,"CODNATIPI": None
        ,"EmpresaMatrizNfse": None
        ,"GERARTAXFINEMBNFE": None
        ,"CREDICMSCOMBUS": None
        ,"DEFCSTIPI49": None
        ,"CONTINGENCIANFCE": "G"
        ,"LocalEstoqueTerceiro": None
        ,"GERLIVICMSEMPSN": None
        ,"CODFORDIFALIQ": None
        ,"EFDCODTIPTIT": None
        ,"CODCTABCOIPI": None
        ,"COPIASDANFE": Decimal('1')
        ,"NOTAENTAJUSTEST": Decimal('7')
        ,"USAVLRMEDTRANSFEMP": None
        ,"UTILIZASEPPULMAO": "N"
        ,"UTILIZAMDE": "T"
        ,"DTREFPRODREINF": None
        ,"VERSAOGNRE": None
        ,"CALCVENCGNREAPU": None
        ,"LOCALPADECONECT": None
        ,"DEFCSTIPI54": None
        ,"DEFCSTIPI55": None
        ,"VLRSTC180": None
        ,"DEFCSTIPI52": None
        ,"IMPRESSORAETQSEP": None
        ,"CONSDEVTEREVTR2050": None
        ,"DEFCSTIPI53": None
        ,"TipoOperacaoSaidaDifPeso": None
        ,"TIPDATAEVTPAGXIR": None
        ,"WMSDOCASEPBALCAO": "S"
        ,"CSTIPIENT": Decimal('49')
        ,"ENTPENBALCAOWMS": "S"
        ,"ModeloSaidaEstoqueConsignado": None
        ,"ModeloEntradaEstoqueConsignado": None
        ,"CORBLOQUEADO": Decimal('14247526')
        ,"DESRESTRFCPSTCST": None
        ,"TEMCOFINS": "S"
        ,"REG54SEQ997ST": "N"
        ,"ALIQFUNTTEL": None
        ,"ModeloEmail": None
        ,"CONSDEVEVTR2050": None
        ,"NURFECARTACORR": Decimal('36')
        ,"PORTASMTPXML": None
        ,"DTCERTIFNFEFIM": None
        ,"CLASCONS_GAS": None
        ,"WMSARMTOTALCOL": "N"
        ,"TIPOIMPKITFOX": "C"
        ,"CODPARCNFCE": None
        ,"ENVINUTNOTAEXC": None
        ,"REABCOMPLETO": "N"
        ,"VALIDACPFCNPJ": "N"
        ,"NURFE": Decimal('3')
        ,"RESPENTREINF": None
        ,"JOBKEYNDD": None
        ,"TOPSANGSUPRI": None
        ,"CODRESPRETC180": None
        ,"NOTAENTAJUSTERECLAS": None
        ,"CAFIR": None
        ,"TIPOATIVIDADEPISCOFINS": Decimal('9')
        ,"BancoIpi": None
        ,"NOTASAIAJUSTESTCTER": None
        ,"GERCTECREDPISCOF": None
        ,"CODTRIB50SUSP": Decimal('0')
        ,"IDENTECT": None
        ,"IGPERMCOMPPRODS": "N"
        ,"ModeloDanfeContingencia": None
        ,"CODCTAPIXTEF": None
        ,"ALIQFUST": None
        ,"ENTAUTTARMAPA": "N"
        ,"DEDUZFCPBCPISCOFINS": None
        ,"EnderecoArmazenagemChk": None
        ,"TipoOperacaoIpi": None
        ,"IMPCTEEMISPROP": "S"
        ,"CONSREPICMSBASEPISCOF": "S"
        ,"ALIQCFMULT": None
        ,"COMPIPISEPICM": "N"
        ,"NomeTabelasPrecoFilha": None
        ,"CALCFUNRURAL": "S"
        ,"TIPDATAEVTPAG": None
        ,"CODMODRETESTWMS": None
        ,"NOTASAIAJUSTESTDTER": None
        ,"INIBEREABMAXPICKING": None
        ,"Parceiro2": None
        ,"DTOPMULTA": None
        ,"EmpresaCadastro": None
        ,"TIPOIMPRESSORA": None
        ,"CODMODEMAILNFE": None
        ,"ULTNSUCTE": Decimal('0')
        ,"EFDTIPREENCHNOTA": None
        ,"WMSUSAETIQPAL": None
        ,"TIPDATAEVTSERV": None
        ,"DESCRICAO": None
        ,"PlanoContaEmpresa": None
        ,"EFDH010_TER": None
        ,"CODSMTP": None
        ,"TOPENTDIFPESOWMS": None
        ,"PERCCUSVAR": Decimal('0')
        ,"GERCIAPCOMPEFD": None
        ,"CabecalhoNotaWmsEnt": None
        ,"TRIBPISCFJUROS": "N"
        ,"TIPOPIX": "N"
        ,"TEMCSSL": "S"
        ,"SERIETOPDIFMAIOR": None
        ,"HORAINICIAL": Decimal('1')
        ,"ALIQPISMULT": None
        ,"DTCERTIFNFEINI": None
        ,"DIRFPLPRIASS": None
        ,"CODENQIPIENT": None
        ,"GERARRETENCAO": None
        ,"DIRFNATDECL": None
        ,"TIPOENVIONFCOM": None
        ,"CODSTPISCFJUROS": None
        ,"PERCMARGEM": Decimal('0')
        ,"PRAZORCANCCTE": None
        ,"CONTINGENCIANFCOM": None
        ,"PERMOUTROUSUSEPPED": "N"
        ,"TIPODANFE": "R"
        ,"CREDPIS": "S"
        ,"CODENDCROSSDOCK": None
        ,"REGIMEESPTRIBISS": None
        ,"ENDECKTINDEF": None
        ,"TIPOENVIONFE": "A"
        ,"CODCTACTBDESC": None
        ,"UTILIZAEXPLOTESEP": "N"
        ,"CODMODNFCESIMPL": None
        ,"CONESTORIGPROD": None
        ,"ALIQCFJUROS": None
        ,"WMSDOCAREP": None
        ,"CODTRIB30": Decimal('0')
        ,"FRETESEPSEMPRE": "N"
        ,"CALCICMSSTNAOCONT": None
        ,"EFDCODTIPOPER": None
        ,"TRIBREINF": None
        ,"STINCLUSA70": "N"
        ,"TRATSOBFINCONF": None
        ,"BLQNFACOMPNFCPEND": None
        ,"NFE": Decimal('2')
        ,"VINCULOEFR": None
        ,"EMPCENTRALMOVFIN": None
        ,"CONICMSMAJFCPINT": None
        ,"VERSAONTCTE": Decimal('9999')
        ,"STATUS": Decimal('0')
        ,"NOTASAIAJUSTEST": Decimal('9')
        ,"FISTEL": None
        ,"GEROBSNOTAG4000": None
        ,"SERIEDEVWMS": None
        ,"CODFORMPREC": None
        ,"NOMECONTADOR": None
        ,"EmpresaOC": None
        ,"CPFCONTADOR": None
        ,"SERIETOPDIFMENOR": None
        ,"TPASSINANTE": None
        ,"ConfiguracaoMeta": None
        ,"CODMETA": None
        ,"DTVALINIREINF": None
        ,"INDESCRIT": Decimal('2')
        ,"INTEGRARIPIFIN": None
        ,"DTREFPREPRODREAISREINFG4000": None
        ,"PARTICMETA": None
        ,"GERCHAVEREFSIG": None
        ,"VERSAOMDFE": Decimal('300')
        ,"TIPOENVIOCTE": "A"
        ,"RelatorioMinutaDespacho": None
        ,"TRATARTRIBUTDEFEMP": "S"
        ,"DIRFPGFUNDPUB": None
        ,"CODTRIB53": "I"
        ,"ContaBancaria": None
        ,"CODLOJAECONECT": None
        ,"DIRFPGEXT": None
        ,"CODPARCCTB": Decimal('0')
        ,"CODTAB": None
        ,"LocalPadraoEconet": None
        ,"EmpresaFrete": None
        ,"EFDCODCENCUS": None
        ,"ATUALCBENEFFAT": None
        ,"VLRBASESTC180": None
        ,"USARECPARCIAL": "N"
        ,"CODEMPORIGMOVFIN": None
        ,"MDFEDOCSEMISPROPRIA": None
        ,"CODTABALT": None
        ,"MAXDEBINDENIZ": None
        ,"CODTRIB61": "I"
        ,"DTINICIOKARDEX": None
        ,"COMPIPI": "N"
        ,"GERNOTAENTCANC": "N"
        ,"TipoOperacaoEntrDifPeso": None
        ,"CORTEFALTAWMS": "N"
        ,"TIPODACTE": Decimal('1')
        ,"EnderecoArmazenagemEsp": None
        ,"TOKENNFSE": None
        ,"TOPSATECONECT": None
        ,"CLASCONS_AGUA": None
        ,"DTREFPRODREINFG4000": None
        ,"CALCPISCFSFIN": None
        ,"NomeTabelaPrecoFilha2": None
        ,"CODMODDANFE": None
        ,"REGAPURTRIBSN": None
        ,"TipoTituloIpi": None
        ,"MARCANOTRPS": "N"
        ,"PRZTOLCANNOTA": Decimal('24')
        ,"ULTPAGLIVISS": None
        ,"CODSTPISCFMULT": None
        ,"CORENCAIXADO": Decimal('14729792')
        ,"DENUNCESPCTE": None
        ,"TipoOperacaoDevMerc": None
        ,"USADTFABLOTNFE": "N"
        ,"USATRIBUTITENS": "N"
        ,"ULTPAGCIAPMODC": None
        ,"SEQTOKENNFCE": Decimal('0')
        ,"QTDCARNFSEOBSITERPS": None
        ,"DTTRANSFFINSLUCR": None
        ,"PRODEPE": "N"
        ,"EFDDIAVENC": None
        ,"ModeloNotaFiscalEstoque": None
        ,"CODCENCUS": None
        ,"VERSAOCTE": Decimal('300')
        ,"COPIASDANFECONTING": Decimal('1')
        ,"CODTRIB20RED": Decimal('0')
        ,"REDDIFALBCPISCOF": None
        ,"IMPETQVOL": Decimal('0')
        ,"EFDH010": None
        ,"TIPICMSFENVALBEM": None
        ,"CODTRIB90CREDDEB": None
        ,"NFSE": None
        ,"ENVINFISSSOMDEVIDO": None
        ,"ICMSSCTTD": None
        ,"CODTIPOPERACOMP": None
        ,"WMSUSAREGVOLREC": "N"
        ,"GEROBSIPIREGENT": None
        ,"RUPTURAEST": "N"
        ,"CONSENTRPENDWMS": "N"
        ,"ParceiroAtivoPj": None
        ,"CTACTBANLREGAPUR": None
        ,"ModeloNotaFiscal": None
        ,"EMPDESTINOWMS": None
        ,"TEMREAICMS": "N"
        ,"CabecalhoNotaWmsSai": None
        ,"TPOEMPRESA": None
        ,"TOPCORBANECONECT": None
        ,"EnderecoArmazenagem": None
        ,"CODMODDACTE": None
        ,"USACUSTOMEDIOMPS": "N"
        ,"CODTIPPARC": Decimal('0')
        ,"PRIORCODNAT": None
        ,"CORAGENDADO": Decimal('6720729')
        ,"NUNOTAMODFX": Decimal('213')
        ,"QTDCONFENTWMS": None
        ,"INDTIPLAYOUTK010": None
        ,"EmpresaNegociacao": None
        ,"NOTAENTAJUSTESTCONS": None
        ,"EFDCODCTABCOINT": None
        ,"CONSIDQTCARCDESC": None
        ,"CREDICMSCST60AM": None
        ,"USAINFOADCONFPED": None
        ,"SERIEACOMPCF": None
        ,"GER0220UNDFORN": None
        ,"CGCPROCURADOR": None
        ,"ESCRITCOMPRAEMISSPROP": None
        ,"PERCCFSERVICO": None
        ,"CODBCOIPI": None
        ,"USATROCOCHECKOUT": "S"
        ,"CALCFETHAB": None
        ,"STINCLUSA": Decimal('0')
        ,"CERTIFICADOPIX": None
        ,"WMSCODENDGAR": None
        ,"DIFALIQFCPINT": None
        ,"CORFATURADO": Decimal('2708090')
        ,"DESONERAFOLHACPRB": "N"
        ,"PERCPIS": Decimal('0')
        ,"TIPOCORTEWMS": None
        ,"CODCTACTBJUROS": None
        ,"DIRFDEPFUNINV": None
        ,"WMSPERSEPPRODAP": "N"
        ,"TIPICMSTOPENTSIMNAC": "N"
        ,"QTCHECKSEP": None
        ,"ULTDUPL": None
        ,"NATCANPIX": None
        ,"CODEMPGRUPFRETE": None
        ,"CALCISS": "S"
        ,"COMPLITEMNOTA": None
        ,"UTILIZATRICROSSDOCKING": "N"
        ,"TPOBSFING4000": None
        ,"AMBIENTEREINF": None
        ,"CentroResultadoDespesa": None
        ,"TipoOperacaoPedidoAgrupa": None
        ,"CODEMP": Decimal('4')
        ,"INTEGRAWMSPROD": "N"
        ,"ALIQPISJUROS": None
        ,"CODMODDANFECONTINGENCIA": None
        ,"EMAILNOTFECREINF": None
        ,"QTPEDSEPAGR": None
        ,"IPIINCICMS": "N"
        ,"TIPOEXPLORACAO": None
        ,"IGCERTIFSMTPXML": None
        ,"WMSINFOPESODETVOL": "N"
        ,"TIPOATIVIDADE": Decimal('1')
        ,"TIPOENVIONFCE": "A"
        ,"CONSOUTROSIMP": "N"
        ,"GERALCDPR": None
        ,"REDISSBCPISCONF": None
        ,"VERSAONFE": Decimal('600')
        ,"INDUNIAO": None
        ,"TIPGERINFGVEICGREB": None
        ,"VLRSTFCPOPANT": None
        ,"TRIBPISCFDESC": "N"
        ,"CODENDDIVERG": None
        ,"ModeloEntradaEstoqueDeTerc": None
        ,"LOCALPAD": Decimal('101')
        ,"CODCONTRINFSE": None
        ,"TIRASERVLRCONTAB": "N"
        ,"TRABCOMIPI": "N"
        ,"NROMAXPROD": None
        ,"ModeloSaidaEstoqueComTerc": None
        ,"SOMARFCPBCCIAP": None
        ,"GRAVAROBSNOTA": "N"
        ,"DIRFCPFRESP": None
        ,"PARTCANALVERDE": "N"
        ,"JUSINUTNOTAEXC": None
        ,"PROXEXECSMTPXML": None
        ,"CODCENCUSDESP": None
        ,"CODRELMINUTAODP": None
        ,"GERNOTAENT": "S"
        ,"USACUSMEDICMPRO": "S"
        ,"SENHASMTPXML": None
        ,"PROJONLINE": "N"
        ,"DESCRNAT": None
        ,"PlanoContaJuro": None
        ,"CODGRUPOTENSAO": None
        ,"DIRFDHEVENTO": None
        ,"IMPETIQSEPOC": "N"
        ,"EmpresaModelo": None
        ,"INCENTCULT": None
        ,"WMSMULTIUSUCONF": "N"
        ,"EFDCODNATDESPRECICMS": None
        ,"AEDFE": None
        ,"USADTVALLOTNFE": "N"
        ,"ModeloDanfeNFCeSimplificado": None
        ,"ENVIOSINCRONONFCE": "S"
        ,"INIBELOTE": "N"
        ,"INCENTFISCALISSQN": "N"
        ,"TIPCONEXSMTPXML": None
        ,"CONSVLRLIQNFSE": "N"
        ,"REDICMSBCPISCONFINS": "N"
        ,"CONTBAIBEMSUBIMPREC": None
        ,"TPLIGACAO": None
        ,"NURFEPRODUCAO": None
        ,"REABCORRECAOWMS": "N"
        ,"CODTRIB90OUT": Decimal('0')
        ,"CORATENDIDO": Decimal('5025874')
        ,"CODTRIB60STANT": Decimal('0')
        ,"TPAMBCTE": Decimal('2')
        ,"NOTAENTSOBRAWMS": None
        ,"CODTRIB41NAOTRIB": Decimal('0')
        ,"CALCICMSAT": None
        ,"CODENDARMINDEF": None
        ,"EMAILCONTADOR": None
        ,"CONSIDBENEF": None
        ,"PROIBESCCHECKOUTPED": "N"
        ,"CALCIRRF": "S"
        ,"CODRECEITAREINF": None
        ,"NUNOTADEMFX": Decimal('213')
        ,"ALIQCFBONIF": None
        ,"CODRECEITAIPI": None
        ,"PROGAQUISALIM": "N"
        ,"CODCTACTBBONIF": None
        ,"EMITEEXPED": "S"
        ,"NaturezaReceitaDespesaICMS": None
        ,"WMSRASTSERMED": None
        ,"DIRFDEPDECJUD": None
        ,"ENVRESPCONTNFE": "N"
        ,"CentroResultadoEFDEmpresa": None
        ,"PlanoContaBonificacao": None
        ,"IDENTECTRASTREIO": None
        ,"SENHANFSE": None
        ,"SUPRIMIREMAILDEST": None
        ,"NaturezaIpi": None
        ,"ALTCONTADOR": "N"
        ,"ENVIOSINCRONONFE": None
        ,"CODTIPOPERIPI": None
        ,"TRATARDIFPARC": "N"
        ,"CODEMPMATRIZGNRE": None
        ,"FormulaDiferencialAliquota": None
        ,"CabecalhoNotaModeloAgenda": None
        ,"ModeloEntradaEstoqueComTerc": None
        ,"CODPARCIPI": None
        ,"VLRSTOPANT": None
        ,"CRCCONTADOR": None
        ,"METCALCDIFICMS": "I"
        ,"NFESTANTCONSFINAL": None
        ,"NOTAMODELODAGENDA": None
        ,"LIVRO1PARA1TGFITE": "S"
        ,"ENVIOSINCRONOCTE": "N"
        ,"TPAMBMDFE": Decimal('2')
        ,"SALDOLIVQUINZIPI": "M"
        ,"GERAGNRE": "S"
        ,"RASTRESTOQUE": "E"
        ,"CODTRIB51DIF": Decimal('0')
        ,"CHAVEACESSONFSE": None
        ,"MAXCREDINDENIZ": None
        ,"DTREFPREPRODFICTREINF": None
        ,"ARQMODBOLETO": None
        ,"CODENDWMS": None
        ,"UTILIZADFETRANSP": "S"
        ,"INIBLOQREGCONF": "N"
        ,"INTFINOBRICMSSTREC": None
        ,"Banco": None
        ,"CNPJEFRVINC": None
        ,"SERVIDORSMTPXML": None
        ,"TOPNFCEECONECT": None
        ,"USAMOVVERTWMS": "N"
        ,"CabecalhoNotaModeloSaidaBem": None
        ,"TOPSAIDADIFPESOWMS": None
        ,"DTOPJUROS": None
        ,"ENVLEITRANSPTOTOBS": None
        ,"CODEMPMATRIZEFD": None
        ,"DESAPCPRODEPE": None
        ,"PERCCSL": None
        ,"VOLCHECKSEPROD": None
        ,"CODCENCUSIPI": None
        ,"USUARIONFSE": None
        ,"GRAVAROBSPADRAO": "N"
        ,"MSGINFADICFETHAB": None
        ,"CODENDAVARIA": None
        ,"LAYOUTDANFE": None
        ,"COPIASDACTE": None
        ,"ModeloEstornoWMSDevCompra": None
        ,"TIPTRANSMNFSE": "A"
        ,"MARGSEGPCP": None
        ,"DEFCSTIPI99": None
        ,"DIRFSITESP": None
        ,"NOTASAIAJUSTESTCONS": None
        ,"EnderecoArmazenagemFlutuante": None
        ,"USASTEXTNOTARESTST": "N"
        ,"NATPESSOAJURIDICA": "00"
        ,"PERPROJ": None
        ,"EmpresaMatriz": None
        ,"TRATOCWMS": "N"
        ,"UTILIZAWMS": "N"
        ,"USANOMECOMPLITEM": "N"
        ,"EFDH010_PRTER": None
        ,"ReceitaDarfReinf": None
        ,"GERLDPERTRI": None
        ,"CODEMPIMPOSTO": None
        ,"RelatorioEtiquetaVolume": None
        ,"TELCONTADOR": None
        ,"TipoOperacaoEntrMerc": None
        ,"EMPADMPUBDIR": "N"
        ,"CONECTORNFSE": None
        ,"MODEMAILLIBLIM": None
        ,"EMPSOMA": Decimal('1')
        ,"NFECANEXTCANMES": "S"
        ,"CSTNREDICMSBCPISCOF": None
        ,"ULTPAGLIVIPI": None
        ,"CODSTPISCFDESC": None
        ,"ORIGDESCONTOS": None
        ,"GERARLIVROS": "S"
        ,"DIAVENCIPI": None
        ,"CODTRIB40ISENT": "I"
        ,"FILTROALIQICMSSQL": None
        ,"CODTIPTITIPI": None
        ,"DTOBITO": None
        ,"GERARPRODLIVENT": "N"
        ,"CONSDEVNFEREINF": None
        ,"IMPNFEEMISSPROP": "S"
        ,"ULTPAGLIVICMS": None
        ,"ENVRESPCONTCTE": None
        ,"IPITRIBUTDEFEMP": "S"
        ,"HORAFINAL": Decimal('23')
        ,"MODDUPL": None
        ,"GERARPRODORIGKIT": "N"
        ,"TRIBPISCFBONIF": None
        ,"CREDCOFINS": "S"
        ,"QTDLIMITEMES": "180"
        ,"UFCRCCONTADOR": None
        ,"NOTASAIAJUSTERECLAS": None
        ,"CSTIPISAI": Decimal('99')
        ,"ORIGPRODCOMIPI": None
        ,"ENVEMAILCONF": None
        ,"TIPCTACTBEFD": "T"
        ,"PERCCFOUTROS": None
        ,"ALIQPISDESC": None
        ,"QRCODENFCEVERSAO2": "S"
        ,"MODESTCPAWMS": None
        ,"SEPPULPARCIAL": "N"
        ,"DTREFPREPRODREAISREINF": None
        ,"AMBIENTEGNRE": None
        ,"PlanoContaDesconto": None
        ,"FLEX": "N"
        ,"ULTPAGLIVENTRAD": None
        ,"CLIENTIDPIXCHECKOUT": "eyJpZCI6ImVmMjczY2ItNyIsImNvZGlnb1B1YmxpY2Fkb3IiOjAsImNvZGlnb1NvZnR3YXJlIjoxMjYyOCwic2VxdWVuY2lhbEluc3RhbGFjYW8iOjF9"
        ,"CODTRIB70REDST": Decimal('0')
        ,"RelatorioCartaCorrecaoCte": None
        ,"JOBMDENDDIGITAL": None
        ,"IMPEXPED": None
        ,"TOKENNFCE": "189d89de4a3d773d7cb934c429b133f3"
        ,"DESRESTRFCPCST": None
        ,"VLRLIQITEMNFCE": "N"
        ,"CCM": None
        ,"MODETQVOL": None
        ,"LocalEstoqueWms": None
        ,"NUMDOCR2020": None
        ,"USASEPAGRUPROD": "N"
        ,"ReceitaDarf": None
        ,"CLIENTSECRETPIXCHECKOUT": "eyJpZCI6ImNmNDNiM2ItIiwiY29kaWdvUHVibGljYWRvciI6MCwiY29kaWdvU29mdHdhcmUiOjEyNjI4LCJzZXF1ZW5jaWFsSW5zdGFsYWNhbyI6MSwic2VxdWVuY2lhbENyZWRlbmNpYWwiOjEsImFtYmllbnRlIjoicHJvZHVjYW8iLCJpYXQiOjE2MTM1NjgyMTkwNzB9"
        ,"CHAVEPIXCHECKOUT": "administrativo@sankhya.com.br"
        ,"CALCICMS": "S"
        ,"VERSAONT": Decimal('9999')
        ,"PRAZOTCANCCTE": None
        ,"PROIBDIGCONFENT": None
        ,"USACODBARRASCONCATWMS": "N"
        ,"CODSTPISCFBONIF": None
        ,"CODCLASSIFESTAB": None
        ,"TipoTitulo": None
        ,"WMSLOCALAJEST": None
        ,"REDSTBCPISCOFINS": None
        ,"OBTSTANTMEDENT": None
        ,"ServidorSMTP": None
}

# Gerar o código
property_code = convert_to_property_code(data)
print(property_code)
